name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Generate Package
      run: dotnet pack --configuration Release
    - name: Pub Package
      run: dotnet nuget push "/home/runner/work/ExeCutor/ExeCutor/ExeCutor/bin/Release/ExeCutor.1.0.1-alpha1.nupkg" -k oy2nblughbrdrgowmjyadtc4rpwcwuoubf3j4lqjtdcife -s https://api.nuget.org/v3/index.json --skip-duplicate